name: Build Hugo site and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        TARGET_REPO: qvieth/qvieth.github.io
        # repo secret's name must be also TOKEN
        TOKEN: ${{ secrets.TOKEN }}
        # CNAME: qvieth.github.io
        HUGO_ARGS: --debug
